/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.abc_marathon;

import java.util.Comparator;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Muzamil-M
 */
public class GUI extends javax.swing.JFrame {
    
//    private JTable jTable1;
    private DefaultTableModel tableModel;
   

private void populateTable() throws Exception {
        Vector<Vector<String>> data = DatabaseHelper.getDataAsListOfStringArrays();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        tableModel = (DefaultTableModel) jTable1.getModel();
        // Set the new model to jTable1
        model.setRowCount(0);
        winner.setText("");
for (Vector<String> rowData : data) {
            model.addRow(rowData);
        }


}
  
   private void clearAndSetRowsForWinnersWithLowestTimes() {
         if (tableModel != null) {
            int rowCount = tableModel.getRowCount();
                   // Step 1: Retrieve data from DefaultTableModel into a List<Object[]>
   Vector<Vector<String>> data = new Vector<>();
        for (int row = 0; row < tableModel.getRowCount(); row++) {
            Vector<String> rowData = new Vector<>();
            for (int col = 0; col < tableModel.getColumnCount(); col++) {
                Object value = tableModel.getValueAt(row, col);
                rowData.add(value != null ? value.toString() : ""); // Convert value to String
            }
            data.add(rowData);
        }

        // Step 2: Sort data based on time 
        data.sort(Comparator.comparing(row -> Integer.parseInt(row.get(2)))); 

        // Step 3: Clear existing rows in DefaultTableModel
        tableModel.setRowCount(0);

        // Step 4: Add new rows for winners (top 3 players with lowest times)
        int numWinners = Math.min(data.size(), 3);
        for (int i = 0; i < numWinners; i++) {
            tableModel.addRow(data.get(i));
        }
            // Perform operations with tableModel
        } else {
            System.err.println("tableModel is null in clearAndSetRowsForWinnersWithLowestTimes()");
        }
 
    }


    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
// Assuming "marathon.png" is located in the resources folder or src/main/picture folder of your project
try {
    // Check the path being used
    String imagePath = "picture/maratho.png";
    ImageIcon icon = new ImageIcon("src/main/picture/maratho.png");
        icon2.setIcon(icon);
    
    if (getClass().getResource(imagePath) == null) {
        System.err.println("Resource not found: " + imagePath);
    } else {
        icon = new ImageIcon(getClass().getResource(imagePath));
        icon2.setIcon(icon);
    }
} catch (NullPointerException e) {
    e.printStackTrace();  // Print stack trace for debugging
}

 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        score = new javax.swing.JTextField();
        addRunner = new javax.swing.JButton();
        winner = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        loadData = new javax.swing.JButton();
        viewWinners = new javax.swing.JButton();
        deleteAll = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        icon2 = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome to MC Marathon");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 6, 420, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 48, 509, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setBackground(new java.awt.Color(204, 255, 153));
        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel2.setText("Name:");

        jLabel3.setBackground(new java.awt.Color(204, 255, 153));
        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel3.setText("Time:");

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });

        addRunner.setBackground(java.awt.Color.lightGray);
        addRunner.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        addRunner.setText("Add Runner");
        addRunner.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), null));
        addRunner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRunnerActionPerformed(evt);
            }
        });
        addRunner.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                addRunnerKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(score)
                    .addComponent(name))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addComponent(addRunner, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(score, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addRunner, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 54, -1, -1));

        winner.setFont(new java.awt.Font("Traditional Arabic", 3, 18)); // NOI18N
        winner.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        winner.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(winner, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 258, 418, 29));

        jPanel4.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.shadow"));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(255, 255, 255)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Main Menu");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 50));

        loadData.setBackground(java.awt.Color.lightGray);
        loadData.setText("Load Data");
        loadData.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        loadData.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        loadData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadDataActionPerformed(evt);
            }
        });
        jPanel4.add(loadData, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 100, 50));

        viewWinners.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.default.hoverBorderColor"));
        viewWinners.setText("View Winners");
        viewWinners.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        viewWinners.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        viewWinners.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewWinnersActionPerformed(evt);
            }
        });
        jPanel4.add(viewWinners, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 100, 50));

        deleteAll.setBackground(java.awt.Color.lightGray);
        deleteAll.setText("Delete All");
        deleteAll.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        deleteAll.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        deleteAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAllActionPerformed(evt);
            }
        });
        jPanel4.add(deleteAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 100, 50));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 186, -1, 343));

        jTable1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Name", "Time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 293, 420, 236));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 6, 14, -1));

        icon2.setBackground(new java.awt.Color(255, 255, 255));
        icon2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon2.setIcon(new javax.swing.ImageIcon("E:\\NB Projects\\ABC_Marathon\\src\\main\\picture\\maratho.png")); // NOI18N
        icon2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        icon2.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        getContentPane().add(icon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 170));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void addRunnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRunnerActionPerformed
        // TODO add your handling code here:
        if(name.getText().isBlank()||score.getText().isBlank()){
                     JOptionPane.showMessageDialog(this, "Runner Data is Mandatory");
                    name.setText("");
                    score.setText("");
        }
        else{
      Boolean is = DatabaseHelper.insert(name.getText(), score.getText());
      
         if(is){
            try {
                JOptionPane.showMessageDialog(this, "Runner Added Succesfully");
                populateTable();
            } catch (Exception ex) {
                Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
            }
         }
        }




    }//GEN-LAST:event_addRunnerActionPerformed

    private void loadDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadDataActionPerformed
        try {
            // TODO add your handling code here:
            populateTable();
        } catch (Exception ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_loadDataActionPerformed

    private void viewWinnersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewWinnersActionPerformed
        // TODO add your handling code here:
          if (tableModel != null) {
            int rowCount = tableModel.getRowCount();
             try {
            clearAndSetRowsForWinnersWithLowestTimes();
        } catch (Exception ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
            // Perform operations with tableModel
        } else {
            System.err.println("tableModel is null in clearAndSetRowsForWinnersWithLowestTimes()");
        }
        winner.setText("Winners of the Game");
       
    }//GEN-LAST:event_viewWinnersActionPerformed

    private void deleteAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAllActionPerformed
        // TODO add your handling code here:
Object[] options = { "Yes", "No" };
    int n = JOptionPane.showOptionDialog(new JFrame(),
            "Do you want to delete All Records ?", "",
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null,
            options, options[1]);
    if(n == JOptionPane.YES_OPTION){ // Afirmative
         Boolean flag = DatabaseHelper.truncate();
    try {
        populateTable();
    } catch (Exception ex) {
        Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
    }
        
    }
    if(n == JOptionPane.NO_OPTION){ // negative
        //....
    }
    if(n == JOptionPane.CLOSED_OPTION){ // closed the dialog
        //....
    }        
    }//GEN-LAST:event_deleteAllActionPerformed

    private void addRunnerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addRunnerKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_addRunnerKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addRunner;
    private javax.swing.JButton deleteAll;
    private javax.swing.JLabel icon2;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton loadData;
    private javax.swing.JTextField name;
    private javax.swing.JTextField score;
    private javax.swing.JButton viewWinners;
    private javax.swing.JLabel winner;
    // End of variables declaration//GEN-END:variables
}
